# Generated by Django 4.0.3 on 2022-03-23 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Character",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("vision", models.CharField(max_length=50)),
                ("weapon", models.CharField(max_length=50)),
                ("nation", models.CharField(max_length=100)),
                ("affiliation", models.CharField(max_length=100)),
                ("rarity", models.IntegerField()),
                ("constallation", models.CharField(max_length=100)),
                ("birthday", models.DateField()),
                ("description", models.TextField()),
                ("vision_key", models.CharField(max_length=50)),
                ("weapon_type", models.CharField(max_length=50)),
                ("raw_data", models.JSONField()),
            ],
            options={
                "verbose_name": "Character",
                "verbose_name_plural": "Characters",
                "db_table": "character",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Weapon",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("weapon_type", models.CharField(max_length=50)),
                ("rarity", models.IntegerField()),
                ("base_attack", models.IntegerField()),
                ("sub_stat", models.CharField(max_length=50)),
                ("passive_name", models.CharField(max_length=100)),
                ("passive_description", models.TextField()),
                ("location", models.CharField(max_length=100)),
                ("raw_data", models.JSONField()),
            ],
            options={
                "verbose_name": "Weapon",
                "verbose_name_plural": "Weapons",
                "db_table": "weapon",
                "ordering": ["name"],
            },
        ),
    ]
