# Generated by Django 4.0.3 on 2022-03-24 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0002_character_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="character",
            name="affiliation",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="character",
            name="birthday",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="character",
            name="constallation",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="character",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="character",
            name="name",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="character",
            name="nation",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="character",
            name="rarity",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="character",
            name="vision",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="character",
            name="vision_key",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="character",
            name="weapon",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="character",
            name="weapon_type",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
