# Generated by Django 4.0.3 on 2022-03-24 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0003_alter_character_affiliation_alter_character_birthday_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="character",
            name="raw_data",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
