name: Creates a docker image for production

on:
  push:
    branches: [feature/*, fix/*]

jobs:
  PublishDockerDev:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: "Build:dockerimage"
        uses: docker/build-push-action@v1
        with:
          registry: ghcr.io
          username: imakecodes
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: makecodes/genshin-card-backend
          tags: dev
